(defpackage :grade-school
  (:use :cl)
  (:export :make-school :add :roster :grade))
(in-package :grade-school)
(defconstant +min-grade+ 1)
(defconstant +max-grade+ 12)
(defun make-school ()
  (make-list (1+ +max-grade+)))
(defun roster (school)
  (reduce #'append school))
(defun add (school student grade)
  (and (<= +min-grade+ grade +max-grade+)
       (not (member student (roster school) :test #'string=))
       (setf (nth grade school) 
             (merge 'list (list student) (nth grade school) #'string<))))
(defun grade (school grade)
  (nth grade school))
