#lang racket
(provide list-allergies allergic-to?)
(define allergens
  '(("eggs" . 1)
    ("peanuts" . 2)
    ("shellfish" . 4)
    ("strawberries" . 8)
    ("tomatoes" . 16)
    ("chocolate" . 32)
    ("pollen" . 64)
    ("cats" . 128)))
(define (list-allergies score)
  (foldr (lambda (allergen acc)
           (let ((name (car allergen))
                 (value (cdr allergen)))
             (if (> (bitwise-and score value) 0)
                 (cons name acc)
                 acc)))
         '()
         allergens))
(define (allergic-to? allergen score)
  (member allergen (list-allergies score)))